### ISSUE TITLE
Welcome template links to non-existent image

### ISSUE THREAD

**Issue by a2** [vapor/api-template#2]
The image URL (`https://pbs.twimg.com/profile_images/760551690902900737/9vosg_bf.jpg`) no longer exists. Should it link instead to the `vapor-logo.png` static resource?

**Comment by tanner0101** [comment]
Oops. Yeah, a better way to do that would be to include the image as base64 or have GitHub host it.

**Comment by loganwright** [comment]
This is resolved in last PR 👍
