### ISSUE TITLE
use static key names

### ISSUE THREAD

**Issue by tanner0101** [vapor/api-template#35]
Use static key names to prevent duplicating string constants in `RowConvertible` and `JSONConvertible` methods. 

As discussed in: https://stackoverflow.com/questions/44500421/database-column-names-in-vapor

**Comment by dankorotin** [comment]
@tanner0101 I'm going to do this.

**Comment by hhanesand** [comment]
Swift 4 keypaths! :)

**Comment by tanner0101** [comment]
Swift 4 key paths will be really nice for Fluent's `Updateable` protocol. However, for this, you still need the database column name (string) stored somewhere.
