### ISSUE TITLE
Suggestion - remove global methods

### ISSUE THREAD

**Issue by grosch** [vapor/api-template#63]
I think we should stop using global methods in app.swift, boot.swift, configure.swift, and routes.swift as it goes against the Swift style guide.  I suggest instead using static methods of a singleton, as one possible alternative.

**Comment by 0xTim** [comment]
Have you got a link to that in the Swift style guide? In general I'd agree with you, but things may be different for a `main.swift`

**Comment by grosch** [comment]
https://swift.org/documentation/api-design-guidelines/#general-conventions

**Comment by jdmcd** [comment]
Personally I would argue this case fits point three:

> 3. When function syntax is part of the established domain notation

The domain being `main.swift` semantics. Just my two cents, though :)

**Comment by grosch** [comment]
I'm fine with main.swift having a global method.  But the other files all add global methods as well that just really don't need to be global.

**Comment by 0xTim** [comment]
Closing as this repo has been superseded by vapor/template
