### ISSUE TITLE
Add tags for SPM

### ISSUE THREAD

**Issue by bensyverson** [vapor/api-template#73]
This is a bit of an edge case, but I have a project that wants to import this template, so that it always has an up-to-date "Hello World" for Vapor. Currently I'm bringing it in like this, which just feels... wrong:

```swift
.package(url: "https://github.com/vapor/api-template.git", from: "0.0.0"),
```

It could be helpful to have tags anyway, so users can continue to build new projects in Vapor 3 when 4 is out, etc. 👌

**Comment by 0xTim** [comment]
@bensyverson wouldn't it be easier to just point to the master branch?

**Comment by rafiki270** [comment]
@bensyverson Pointing to master makes an absolute sense to me for the latest code. Or do you want to point to the latest RELEASE, not master?

**Comment by 0xTim** [comment]
Closing as this repo has been superseded by vapor/template
