### ISSUE TITLE
vapor new --template=basic fails.

### ISSUE THREAD

**Issue by xcadaverx** [vapor/api-template#9]
vapor new AppName --template=basic returns:

Cloning Template [Failed]
Error: fatal: repository 'basic' does not exist

**Comment by Casperhr** [comment]
Atm you have to make a full path to git
vapor new test --template=https://github.com/vapor/basic-template

But if you just want the basic template just write
`vapor new test`

read more: https://vapor.github.io/documentation/getting-started/hello-world.html
