### ISSUE TITLE
Update to Vapor 4

### ISSUE THREAD

**Issue by nathanfallet** [vapor/api-template#94]
I just created a project with this template (with `vapor new <name> --template=api`) and I saw it was not using Vapor 4, but Vapor 3.

Also, I am trying to use it with another package which uses a newer version of Swift NIO (used in Vapor 4, but not Vapor 3) so I have dependencies conflicts.

Any plan to update this template (and also other templates by the way) to Vapor 4?

**Comment by nathanfallet** [comment]
Should be fixed by #76

**Comment by 0xTim** [comment]
@NathanFallet you can do `vapor new <name> --branch=4` to get a new Vapor 4 project (or switch to the beta version of the toolbox which uses vapor/template)

**Comment by 0xTim** [comment]
Closing as this repo has been superseded by vapor/template
